osx_image: xcode9
language: objective-c
# cache: cocoapods
xcode_project: OpenCallBlock.xcodeproj # path to your xcodeproj folder
xcode_scheme: OpenCallBlock

cache:
  directories:
  - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds
